### ISSUE TITLE
Redesign query tool

### ISSUE THREAD

**Issue by crijke** [datenguide/datenguide#106]
- Make it more 'content page-like' with filterbar on top and breadcrumbs instead of sidebar.
- put description on top, only keep data an api tabs in table

from fact view ticket:

generate region breadcrumb with 'Home', 'Bundesland', 'Regierungsbezirk', 'Kreis', ('Gemeinde')
generate attribute breadcrumb with 'Home', 'Attribute', 'Argument'
generate teaser from attribute docs
generate headline with attribute label and year
generate table (region is fix, columns: years, argument)
make table sortable
build .csv download button (with nice filenames)
generate check list of attributes / arguments for this topic
change table on checked arguments

**Comment by sjockers** [comment]
This has been implemented apart from 'make table sortable'. We'll close this issue for now.
